name: build WED conf=release_opt

on:
  push:
  workflow_dispatch:
    inputs:
      version_string:
        description: 'Enter the version string e.g. 250r3'
        required: false 
        type: string

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference 
      run: |
        msbuild /m /p:Configuration=Release /p:Platform="x64" /t:WorldEditor msvc\XPTools.sln
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wed_release_build
        path: |
          msvc\WorldEditor\Release\WorldEditor.exe
          src\WEDCore\README.WorldEditor
          
  build-mac:
    runs-on: macos-11
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: yes
      - name: Setup Credentials
        uses: apple-actions/import-codesign-certs@v2
        with: 
          p12-file-base64: ${{ secrets.APPLE_DEV_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_DEV_CERTIFICATE_PASSWORD }}
      - name: Build Libs
        run: |
          git submodule init
          git submodule update libs
          cd libs
          make -j$(sysctl -n hw.logicalcpu)
      - name: Build
        env:
          scheme: "WED"
          config: "Release"
        run: |
          xcodebuild -scheme "$scheme" -config "$config" -project SceneryTools.xcodeproj -archivePath build/WED.xcarchive CODE_SIGN_STYLE="Manual" CODE_SIGN_IDENTITY="Developer ID Application: Laminar Research (LPH4NFE92D)" archive | xcpretty && exit ${PIPESTATUS[0]}
      - name: Notarize App
        run: |
          ./build-tools/mac/notarization.sh WED.zip build/WED.xcarchive/Products/Applications/WED.app staple
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wed_release_build
          path: |
            build/WED.xcarchive/Products/Applications/WED.app
            src/WEDCore/README.WorldEditor
          
  build-linux:
    runs-on: ubuntu-22.04
    # we need fltk-dev and python 2.7
    container:
        image: ghcr.io/x-plane/xptools_builder:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build Libs
        run: |
          git config --global --add safe.directory /__w/xptools/xptools
          git submodule init
          git submodule update libs
          cd libs
          make -j$(nproc)
      - name: Build
        run: |
          make -s -C . conf=release_opt -j$(nproc) WED
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wed_release_build
          path: |
            build/Linux/release_opt/WED
            src/WEDCore/README.WorldEditor
