name: Linux

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/x-plane/xptools_builder:latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Libs
        run: |
          git submodule init
          git submodule update libs
          cd libs
          CC=gcc-7 CXX=g++-7 make
      - name: Build
        env:
          scheme: "WED"
          config: "Release"
        run: |
          CC=gcc-7 CXX=g++-7 make -s -C . conf=release_opt -j$(nproc) WED
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wed_linux_
          path: |
            build/Linux/release_opt/WED
            src/WEDCore/README.WorldEditor
          if-no-files-found: error
