name: Xcode - Build and Analyze

on: [push]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: yes
      - name: Build
        env:
          scheme: "WED"
          config: "Release"
        run: |
          xcodebuild -scheme "$scheme" -config "$config" -project SceneryTools.xcodeproj -archivePath WED.xcarchive CODE_SIGN_STYLE="Manual" CODE_SIGN_IDENTITY="Developer ID Application: Laminar Research (LPH4NFE92D)" archive | xcpretty && exit ${PIPESTATUS[0]}
